services:
  postgres:
    image: postgres:18-alpine
    container_name: banking-db
    environment:
      POSTGRES_USER: ndk1996
      POSTGRES_PASSWORD: localpassword@999
      POSTGRES_DB: banking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ndk1996 -d banking_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  banking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking_db
      SPRING_DATASOURCE_USERNAME: ndk1996
      SPRING_DATASOURCE_PASSWORD: localpassword@999
    networks:
      - banking-network

volumes:
  postgres_data:

networks:
  banking-network:
    driver: bridge
